config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :ideas do
    resources :reviews, only: [:create, :destroy]
    resources :likes, only: [:create, :destroy]
  end

  get '/', {to: 'ideas#index', as: 'root'}
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)

    alias_action :create, :read, :update, :destroy, to: :crud
    # Define abilities for the passed in user here. For example:
    #
      user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    can(:crud, Idea) do |idea|
      idea.user == user
    end

    can(:crud, Review) do |review|
      review.user == user
    end

    can(:like, Idea) do |idea|
      idea.user != user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/idea.rb
class Idea < ApplicationRecord
  belongs_to :user

  has_many :reviews, dependent: :nullify
  has_many :likes, dependent: :destroy
  has_many :likers, through: :likes, source: :user

  validates :title, presence: true
  validates :description, presence: true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :idea

  validates :idea, uniqueness: {scope: :user}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :idea
  belongs_to :user

  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord

    has_secure_password

    has_many :reviews, dependent: :nullify
    has_many :ideas, dependent: :nullify
    has_many :likes, dependent: :nullify
    has_many :liked_ideas, through: :likes, source: :idea

    VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
    validates :email, presence: true, uniqueness: true, format: VALID_EMAIL_REGEX
    validates :first_name, presence: true
    validates :last_name, presence: true
    validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_user
        User.find_by(id: session[:user_id])
    end
    
    helper_method :current_user

    def authenticate_user!
        redirect_to new_session_path, alert: 'you must sign in to access this page.' unless current_user
    end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController

  before_action :find_idea, only: [:show, :destroy, :edit, :update]
  before_action :authenticate_user!, except: [:show, :index]
  before_action :authorize, only: [:edit, :update, :destroy]

  def new
    @idea = Idea.new
  end

  def create
    @idea = Idea.new idea_params
    @idea.user = current_user
    if @idea.save
      redirect_to @idea
    else
      render :new
    end
  end

  def show
    @review = Review.new
    @review.idea = @idea
    @reviews = @idea.reviews.all.order(created_at: :desc)
  end

  def index
    @ideas = Idea.all.order(created_at: :desc)
  end

  def destroy
    @idea.destroy
    redirect_to root_path, notice: 'your idea is gone. give us your new idea when it comes!'
  end

  def edit
  end

  def update
    if @idea.update idea_params
      redirect_to @idea, notice: 'your freshly updated idea is here!'
    else
      render :edit
    end
  end

  private
  def idea_params
    params.require(:idea).permit(:title, :description)
  end

  def find_idea
    @idea = Idea.find_by(id: params[:id])
  end

  def authorize
    return redirect_to @idea, alert: 'you can only edit or delete your own ideas' unless can?(:crud, @idea)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :find_idea
  before_action :authenticate_user!
  before_action :authorize

  def create
    @like = Like.new
    @like.user = current_user
    @like.idea = @idea
    if @like.save
      redirect_to @idea
    end
  end

  def destroy
    @like = Like.find_by(id: params[:id])
    @like.destroy
    redirect_to @idea
  end

  private
  def find_idea
    @idea = Idea.find params[:idea_id]
  end

  def authorize
    return redirect_to @idea, alert: "sorry, not allowed, but you can like other people's ideas though!" unless can?(:like, @idea)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :find_review, only: [:show, :destroy]
  before_action :authenticate_user!, only: [:create, :destroy]
  before_action :authorize, only: [:destroy]

  def create
    @review = Review.new review_params
    @review.idea = Idea.find params[:idea_id]
    @review.user = current_user
    if @review.save
      redirect_to @review.idea, notice: 'your review is published.'
    else
      render 'ideas/show'
    end
  end

  def destroy
    @review.destroy
    redirect_to @review.idea, notice: 'gone as if it never happened!'
  end

  private
  def review_params
    params.require(:review).permit(:title, :description)
  end

  def find_review
    @review = Review.find_by(id: params[:id])
  end

  def authorize
    return redirect_to @review.idea, alert: 'you can only edit or delete your own reviews' unless can?(:crud, @review)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new, alert: 'are you sure about that? if you are not a current idea factory contributer, please sign up first.'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private
  def sign_in_params
    params.require(:user).permit(:email, :password)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      redirect_to new_session_path, notice: 'please sign in with your newly created credentials!'
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/ideas/create.html.erb
<h1>Ideas#create</h1>
<p>Find me in app/views/ideas/create.html.erb</p>

app/views/ideas/delete.html.erb
<h1>Ideas#delete</h1>
<p>Find me in app/views/ideas/delete.html.erb</p>

app/views/ideas/edit.html.erb
<h1>Revise your thoughts here...</h1>

<%if @idea.errors.any?%>
<p>Wait!!</p>
<%@ideas.errors.full_messages.each do |error|%>
<p><%=error%></p>
<%end%>
<%end%>

<%=form_with model: @idea, local: true do |f|%>
<div>
<%=f.label :title%>
<%=f.text_field :title%>
</div>
<div>
<%=f.label :description%>
<%=f.text_field :description%>
</div>
<%=f.submit 'Send updates to idea factory!'%>
<%end%>

app/views/ideas/index.html.erb
<h1>Get your mind refreshed!!</h1>

<%@ideas.each do |idea|%>
<div>
    <h3><%=link_to idea.title, idea%></h3>
    <p><%=idea.description%></p>
    <ul>
        <li>By: <%=idea.user.first_name%></li>
        <li>Likes: <%=idea.likers.count%></li>
    </ul>
</div>
<%end%>

app/views/ideas/new.html.erb
<h1>Write a new idea</h1>

<%if @idea.errors.any?%>
<p>Wait!!</p>
<%@idea.errors.full_messages.each do |error|%>
<p><%=error%></p>
<%end%>
<%end%>

<%=form_with model: @idea, local: true do |f|%>
<div>
<%=f.label :title%>
<%=f.text_field :title%>
</div>
<div>
<%=f.label :description%>
<%=f.text_field :description%>
</div>
<%=f.submit 'Send to idea factory!'%>
<%end%>

app/views/ideas/show.html.erb
<h1><%=@idea.title%></h1>
<p><%=@idea.description%></p>
<% if can?(:like, @idea)%>
<%like = Like.find_by(idea_id: @idea.id)%>
<% if @idea&.likers&.include? current_user%>
<%=link_to 'liked', idea_like_path(@idea, like), method: :delete%>
<%else%>
<%=link_to 'Like', idea_likes_path(@idea), method: :post%>
<%end%>
<%end%>
<ul>
   <li>By: <%=@idea.user.first_name%></li>
   <li>Likes: <%=@idea.likers.count%></li>
</ul>

<% if can?(:crud, @idea)%>
<%=link_to 'Edit', edit_idea_path(@idea)%>
<%=link_to 'Delete', @idea, method: :delete, data: {confirm: 'forget this idea?'}%>
<%end%>

<h5>Add Review</h5>
<%=form_with(model:[@idea, @review], local: true) do |f|%>
<%=f.text_area(:description, placeholder: 'what are your thoughts?')%>
<%=f.submit 'Send off your review!'%>
<%end%>

<%@reviews.each do |review|%>
<div>
    <p><%=review.description%></p>
    <small>By: <%=review.user.first_name%></small>
    <small><%=time_ago_in_words(review.created_at)%> Ago</small>
    <% if can?(:crud, review)%>
    <small><%=link_to 'Delete', idea_review_path(review.idea, review), method: :delete, data: {confirm: 'let it be no more?'}%></small>
    <%end%>
</div>
<%end%>

app/views/ideas/update.html.erb
<h1>Ideas#update</h1>
<p>Find me in app/views/ideas/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaFactory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <nav>
    <%=link_to 'Home', root_path%>
    <% if current_user%>
    <p>Welcome back, <%=current_user.first_name%>!</p>
    <%=link_to 'Have an Idea?', new_idea_path%>
    <%=link_to 'Sign Out', session_path, method: :delete%>
    <%else%>
    <%=link_to 'Sign In', new_session_path%>
    <%end%>
</nav>

<% flash.each do |type, message| %>
<div class="flash flash-<%= type %>">
    <%= message%>
</div>
<%end%>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Contribute to idea factory?</h1>

<% if @user.errors.any?%>
<p>Wait!!</p>
<% @user.errors.full_messages.each do |error| %>
<p><%=error%></p>
<%end%>
<%end%>

<%=form_with model: @user, local:true do |f|%>
<div>
    <%=f.label :first_name%>
    <%=f.text_field :first_name%>
</div>
<div>
    <%=f.label :last_name%>
    <%=f.text_field :last_name%>
</div>
<div>
    <%=f.label :email%>
    <%=f.email_field :email%>
</div>
<div>
    <%=f.label :password%>
    <%=f.password_field :password%>
</div>
<div>
    <%=f.label :enter_password_again%>
    <%=f.password_field :password_confirmation%>
</div>
<%=f.submit 'Submit'%>
<%end%>